HTAdmin/HTAdmin/Controllers/Book/BookSmartDeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HTAdmin.Models;
using htBLL;

namespace HTAdmin.Controllers.Book
{
    public class BookSmartDeviceController : Controller
    {
        //
        // GET: /BookSmartDevice/
       // public IEnumerable<SelectListItem> selectList;

        public ActionResult DeviceDetailsFromLeftMenu()
        {
            return View("DeviceDetails", GetDeviceDetailsFromLeftMenu());
        }

        public ActionResult DeviceDetails()
        {
            return View("DeviceDetails", GetDeviceDetails());
        }
        public ActionResult EquipmentInformation()
        {
            return View("EquipmentInformation", GetEquipmentInformation());
        }
        public ActionResult CustomerInformation()
        {
            return View("CustomerInformation", GetCustomerInformation());
        }
         public ActionResult RepairQuotes()
         {
             return View("RepairQuotes", GetRepairQuotes());
         }

         public ActionResult RequestSaved()
         {
             return View();
         }
         private DeviceDetails GetDeviceDetailsFromLeftMenu()
         {
             ClearSmartDeviceSessions();
             Session["DeviceDetails"] = new DeviceDetails();
             return (DeviceDetails)Session["DeviceDetails"];
         }
         private void ClearSmartDeviceSessions()
         {
             Session["DeviceDetails"] = null;
             Session["EquipmentInformation"] = null;
             Session["CustomerInformation"] = null;
             Session["RepairQuotes"] = null;
         }
        private DeviceDetails GetDeviceDetails()
        {
            if (Session["DeviceDetails"] == null)
            {
                Session["DeviceDetails"] = new DeviceDetails();
            }
            return (DeviceDetails)Session["DeviceDetails"];
        }

        private EquipmentInformation GetEquipmentInformation()
        {
            if (Session["EquipmentInformation"] == null)
            {
                Session["EquipmentInformation"] = new EquipmentInformation();
            }
            return (EquipmentInformation)Session["EquipmentInformation"];
        }

        private CustomerInformation GetCustomerInformation()
        {
            if (Session["CustomerInformation"] == null)
            {
                Session["CustomerInformation"] = new CustomerInformation();
            }
            return (CustomerInformation)Session["CustomerInformation"];
        }
        private RepairQuotes GetRepairQuotes()
        {
            if (Session["RepairQuotes"] == null)
            {
                RepairQuotes objRepairQuotes= new RepairQuotes();
                Session["RepairQuotes"] = objRepairQuotes;
            }
            return (RepairQuotes)Session["RepairQuotes"];
        }
        


        private void RemoveCustomer()
        {
            Session.Remove("DeviceDetails");
        }


        public JsonResult GetProductTypes()
        {
            int selectedProductTypeId = 0;
            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.DeviceTypeID != 0)
                {
                    selectedProductTypeId = obj.ProductTypeId;//(obj.DeviceTypeID == null) ? 0 : (Int32)obj.DeviceTypeID;
                }
            }

            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultData = bookSmartDeviceService.GetAllProductType()
                .Select(c => new { Value = c.ProductTypeId, Text = c.Name, Selected = (c.ProductTypeId == selectedProductTypeId) ? 1 : 0 }).ToList();


            
            return Json(new { result = resultData }, JsonRequestBehavior.AllowGet);
            //list.Where(w => w.Name == "height").ToList().ForEach(s => s.Value = 30);
        }

        public JsonResult GetDeviceTypes()
        {
            int selectedDeviceTypeId=0;
            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.DeviceTypeID != 0)
                {
                    selectedDeviceTypeId = obj.DeviceTypeID;//(obj.DeviceTypeID == null) ? 0 : (Int32)obj.DeviceTypeID;
                }
            }

            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultData = bookSmartDeviceService.GetAllDeviceType()
                .Select(c => new { Value = c.DeviceTypeId, Text = c.Name, Selected = (c.DeviceTypeId == selectedDeviceTypeId) ? 1 : 0 }).ToList();


            
            return Json(new { result = resultData }, JsonRequestBehavior.AllowGet);
            //list.Where(w => w.Name == "height").ToList().ForEach(s => s.Value = 30);
        }

        public JsonResult GetSearchChannels()
        {
            int selectedSearchChannelId = 0;
            CustomerInformation obj = GetCustomerInformation();
            if (obj != null)
            {
                if (obj.SearchChannelId != 0)
                {
                    selectedSearchChannelId = obj.SearchChannelId;//(obj.DeviceTypeID == null) ? 0 : (Int32)obj.DeviceTypeID;
                }
            }
            //obj.lstSearchChannel
            //BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultData = obj.lstSearchChannel
                .Select(c => new { Value = c.SearchChannelId, Text = c.name, Selected = (c.SearchChannelId == selectedSearchChannelId) ? 1 : 0 }).ToList();



            return Json(new { result = resultData }, JsonRequestBehavior.AllowGet);
            //list.Where(w => w.Name == "height").ToList().ForEach(s => s.Value = 30);
        }
        public JsonResult GetHandSetModel(int deviceTypeId)
        {
            int selectedHandsetModelID = 0;
            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.HandsetModelID != 0)
                {
                    selectedHandsetModelID = obj.HandsetModelID; //(obj.HandsetModelID == null) ? 0 : (Int32)obj.HandsetModelID;
                }
            }

            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultHandSetModels = bookSmartDeviceService.GetHandSetModelForDeviceType(deviceTypeId)
                .Select(c => new { Value = c.HandsetModelId, Text = c.Name, Selected = (c.HandsetModelId == selectedHandsetModelID) ? 1 : 0 })
                .ToList();
            return Json(new { result = resultHandSetModels }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetHandSetModelNew(int deviceTypeId, int productTypeId)
        {
            int selectedHandsetModelID = 0;
            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.HandsetModelID != 0)
                {
                    selectedHandsetModelID = obj.HandsetModelID; //(obj.HandsetModelID == null) ? 0 : (Int32)obj.HandsetModelID;
                }
            }

            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultHandSetModels = bookSmartDeviceService.GetHandSetModelForDeviceTypeNew(deviceTypeId,productTypeId)
                .Select(c => new { Value = c.HandsetModelId, Text = c.Name, Selected = (c.HandsetModelId == selectedHandsetModelID) ? 1 : 0 })
                .ToList();
            return Json(new { result = resultHandSetModels }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetHandSetModelSelected()
        {
            int selectedHandsetModelID = 0;

            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.HandsetModelID != 0)
                {
                    selectedHandsetModelID = obj.HandsetModelID;//(obj.HandsetModelID == null) ? 0 : (Int32)obj.HandsetModelID;  
                }
            }
           
            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            DeviceDetails objDeviceType = GetDeviceDetails();
            
            var resultHandSetModels = bookSmartDeviceService.GetHandSetModelForDeviceType(obj.DeviceTypeID)
                .Select(c => new { Value = c.HandsetModelId, Text = c.Name, Selected = (c.HandsetModelId == selectedHandsetModelID) ? 1 : 0 })
                .ToList();
            return Json(new { result = resultHandSetModels }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetColours()
        {
            int selectedDeviceColourID = 0;
            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.DeviceColourID != 0)
                {
                    selectedDeviceColourID = obj.DeviceColourID;
                }
            }

            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultColours = bookSmartDeviceService.GetColours()
                .Select(c => new { Value = c.ColourId, Text = c.colour, Selected = (c.ColourId == selectedDeviceColourID) ? 1 : 0 }).ToList();
            return Json(new { result = resultColours }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetNetworks()
        {
            int selectedNetworkID = 0;
            DeviceDetails obj = GetDeviceDetails();
            if (obj != null)
            {
                if (obj.NetworkID != 0)
                {
                    selectedNetworkID = obj.NetworkID;
                }
            }

            BookSmartDeviceService bookSmartDeviceService = new BookSmartDeviceService();
            var resultColours = bookSmartDeviceService.GetNetworks()
                .Select(c => new { Value = c.NetworkId, Text = c.name, Selected = (c.NetworkId == selectedNetworkID) ? 1 : 0 }).ToList();

HTAdmin/HTAdmin/Controllers/LeftMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HTAdmin.Controllers
{
    public class LeftMenuController : Controller
    {
        //
        // GET: /LeftMenu/

        public ActionResult Index()
        {
            return PartialView();
        }

    }
}

HTAdmin/HTAdmin/Controllers/MasterData/ProductType/ProductTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using htBLL;

namespace HTAdmin.Controllers
{
    public class ProductTypeController : Controller
    {

        public ActionResult ProductType()
        {
            return PartialView();
        }

        //
        // GET: /ProductType/
        [HttpPost]
        public JsonResult ProductTypeList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                ProductTypeServices productTypeServices = new ProductTypeServices();
                var ProdutTypes = productTypeServices.GetAllProdutType();
                var produtTypesCount = ProdutTypes.Count;
                string[] sortParms = jtSorting.Split(' ');
                var produtTypesSorted = productTypeServices.SortObjectList(ProdutTypes, sortParms[0], sortParms[1]);


                return Json(new { Result = "OK", Records = produtTypesSorted, TotalRecordCount = produtTypesCount });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }

        }


        [HttpPost]
        public JsonResult CreateProductType(ProductType productType)
        {
            try
            {
                //productType.AddBusinessRules();
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }
                ProductTypeServices productTypeServices = new ProductTypeServices();
                var addedProductType = productTypeServices.AddProductType(productType);
                return Json(new { Result = "OK", Record = addedProductType });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }


        [HttpPost]
        public JsonResult UpdateProductType(ProductType productType)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }

                ProductTypeServices productTypeServices = new ProductTypeServices();
                productTypeServices.UpdateProductType(productType);

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        
        [HttpPost]
        public JsonResult DeleteProductType(int ProductTypeId)
    {
        try
        {

            ProductTypeServices productTypeServices = new ProductTypeServices();
            productTypeServices.DeleteProductType(ProductTypeId);

            
            return Json(new { Result = "OK" });
        }
        catch (Exception ex)
        {
            return Json(new { Result = "ERROR", Message = ex.Message });
        }
    }
 


    }
}

HTAdmin/HTAdmin/Views/LeftMenu/Index.cshtml
        <div class="left_col scroll-view">

          <div class="navbar nav_title" style="border: 0;">
            <a href="dashboard.html" class="site_title"><i class="fa fa-paw"></i> <span>ht Solution</span></a>
          </div>
          <div class="clearfix"></div>

          <!-- menu prile quick info -->
          <div class="profile">
            <div class="profile_pic">
              <img src="/uploads/user/sant.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2>Santhosh M</h2>
            </div>
          </div>
          <!-- /menu prile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

            <div class="menu_section">
              <h3>General</h3>
              <ul class="nav side-menu">
                <li><a href="dashboard.html"><i class="fa fa-home"></i> Dashboard </span></a>
                </li>
                <li><a><i class="fa fa-edit"></i> Book <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li>@Html.ActionLink("Smart Device", "DeviceDetailsFromLeftMenu", "BookSmartDevice")</li>
                    <li>@Html.ActionLink("Computer", "DeviceDetailsFromLeftMenu", "BookComputer")</li>
                  </ul>
                </li>
                <li><a><i class="fa fa-desktop"></i> Status<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li><a href="#">Collected/Resolved Jobs</a></li>
                    <li><a href="#">Media Gallery</a></li>
                    <li><a href="#">Repair Quotation</a></li>
                  </ul>
                </li>
				<li><a><i class="fa fa-desktop"></i> Others<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li><a href="#">Leads</a></li>
                    <li><a href="#">Refund</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-table"></i> Master Data<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li>@Html.ActionLink("Product Type", "ProductType", "ProductType")</li> 
                    <li>@Html.ActionLink("Contact us", "Contact", "Home")</li>
					<li><a href="#">Model</a></li>
					<li><a href="#">Brand</a></li>
					<li><a href="#">Mobie Network</a></li>
					<li><a href="#">Users</a></li>
					<li><a href="#">Search Channel</a></li>
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Device Colours</a></li>
					<li><a href="#">Suppliers</a></li>
					<li><a href="#">Repair Quotation</a></li>
					<li><a href="#">Stock</a></li>
					<li><a href="#">Stock Status</a></li>
					<li><a href="#">Store Locations</a></li>
                  </ul>
                </li>
                <li><a href="#"><i class="fa fa-bar-chart-o"></i> Reports </span></a></li>
              </ul>
            </div>
            <div class="menu_section">
              <h3>DAILY SUMMARY</h3>
              <ul class="nav side-menu">
                <li><a href="#"><i class="fa fa-bug"></i> Closing Sheet </span></a></li>
                <li><a href="#"><i class="fa fa-windows"></i> Daily Sales Overview</span></a></li>
              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->
        </div>